name: Deploying

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: cloning repo 
      uses: actions/checkout@v3 # checkouts current repo/clone repo 
    - name: npm installing
      run: npm ci 
    - name: run server 
      run: npm run dev
      run: echo " done "

